language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build

branches:
  only:
    - master
    - develop
    
os: linux
arch:
  - ppc64le
dist: focal

deploy:
  provider: pages:git
  cleanup: false
  strategy: git
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: coverage/lcov-report
  target_branch: doc
  on:
    branch: develop
